### ISSUE TITLE
Сделать главную страницу страницей, ведущей на калькуляторы

### ISSUE THREAD

**Issue by optozorax** [optozorax/math_modeling_controllable_systems#2]
* Сделать программный интерфейс, чтобы можно было добавлять новые калькуляторы
* Переместить текущий калькулятор на новый адрес

**Comment by optozorax** [comment]
@Sing3Rous ты получаешь уведомление, если я тебя так призываю?

**Comment by Sing3Rous** [comment]
Создал, переместил
