### ISSUE TITLE
Фронтэнд для ввода матриц

### ISSUE THREAD

**Issue by optozorax** [optozorax/math_modeling_controllable_systems#5]
Сейчас уже имеется страница для решения дифференциального уравнения с матрицами:
http://217.71.129.139:4186/diffur.html

Хочется, чтобы матрицы вводились не таким идиотским образом, а как на всех нормальных сайтах с калькуляторами:
![изображение](https://user-images.githubusercontent.com/18114381/67548038-f99cca00-f72a-11e9-8d5b-1b764974a636.png)

При этом надо учесть, что у нас матрица А обязательно квадратная (то есть размер вводится как на картинке), а все остальные могут быть произвольных размеров.

Так же хотелось бы автоматическую проверку введённых размеров матриц на предмет того, что их возможно перемножить в итоге.

**Comment by optozorax** [comment]
Нашёл пример для неквадратной мартицы:
![изображение](https://user-images.githubusercontent.com/18114381/67548651-85fbbc80-f72c-11e9-8ff3-bdbb26a1bd80.png)

https://www.kontrolnaya-rabota.ru/s/matrix/determination/

**Comment by optozorax** [comment]
@Sing3Rous случится?

**Comment by Sing3Rous** [comment]
> 
> 
> @Sing3Rous случится?

ничто не истина, все дозволено
